---
- name: Reload systemd daemon for user
  systemd:
    daemon_reload: yes
    scope: user
  tags:
    - systemd
    - reload
    - services

- name: Enable and start pod service
  systemd:
    name: dev-pod.service
    enabled: yes
    state: started
    scope: user
  tags:
    - services
    - start
    - systemd
    - pod

- name: Enable and start PostgreSQL service
  systemd:
    name: postgres.service
    enabled: yes
    state: started
    scope: user
  tags:
    - services
    - start
    - systemd
    - database

- name: Enable and start pgAdmin service
  systemd:
    name: pgadmin.service
    enabled: yes
    state: started
    scope: user
  tags:
    - services
    - start
    - systemd
    - database

- name: Enable and start Dashy service
  systemd:
    name: dashy.service
    enabled: yes
    state: started
    scope: user
  tags:
    - services
    - start
    - systemd
    - dashboard

- name: Enable and start Syncthing service
  systemd:
    name: syncthing.service
    enabled: yes
    state: started
    scope: user
  tags:
    - services
    - start
    - systemd
    - syncthing

- name: Enable and start Caddy service
  systemd:
    name: caddy.service
    enabled: yes
    state: started
    scope: user
  tags:
    - services
    - start
    - systemd
    - caddy
    - proxy
