---
- name: Create pod quadlet file
  template:
    src: templates/dev.pod.j2
    dest: "{{ quadlet_dir }}/dev.pod"
    mode: '0644'
  tags:
    - quadlets
    - pod
    - podman
    - containers
    - config
    - network

- name: Create PostgreSQL container quadlet
  template:
    src: templates/postgres.container.j2
    dest: "{{ quadlet_dir }}/postgres.container"
    mode: '0644'
  tags:
    - quadlets
    - database
    - containers
    - podman
    - config

- name: Create pgAdmin container quadlet
  template:
    src: templates/pgadmin.container.j2
    dest: "{{ quadlet_dir }}/pgadmin.container"
    mode: '0644'
  tags:
    - quadlets
    - database
    - containers
    - podman
    - config

- name: Create Dashy container quadlet
  template:
    src: templates/dashy.container.j2
    dest: "{{ quadlet_dir }}/dashy.container"
    mode: '0644'
  tags:
    - quadlets
    - dashboard
    - containers
    - podman
    - config

- name: Create Syncthing quadlet
  template:
    src: templates/syncthing.container.j2
    dest: "{{ quadlet_dir }}/syncthing.container"
    mode: '0644'
  tags:
    - quadlets
    - syncthing
    - containers
    - podman
    - config
