---
- name: Display access information
  debug:
    msg: |
      Services running!
      {% for service in services %}
      {{ service.description }}: {{ service.url }}
      {% endfor %}
      PostgreSQL: {{ base_hostname }}:{{ ports.postrges }}
      Credentials: pgAdmin={{ pgadmin_email }}/{{ pgadmin_password }}, PostgreSQL={{ postgres_user }}/{{ postgres_password }}
  tags:
    - info
    - display
