---
- name: Generate README from template
  template:
    src: templates/README.md.j2
    dest: "{{ readme_path }}"
    mode: '0644'
  tags:
    - info
    - display
    - never

- name: Display README generation message
  debug:
    msg: "README.md has been generated at {{ readme_path }}"
  tags:
    - info
    - display
    - never
